### ISSUE TITLE
TikTok Fails to patch

### ISSUE THREAD

**Issue by dayloon** [taku-nm/auto-cli#30]
Tried to patch TikTok 32.5.3 with the following options : 

-i "Change package name" -i "Show seekbar" -i "Settings" -i "Feed filter"

Keeps coming up with the attached error.
[errors.txt](https://github.com/taku-nm/auto-cli/files/13759791/errors.txt)

Have also included my options.json file
[options.json](https://github.com/taku-nm/auto-cli/files/13759794/options.json)

Selected custom options because i wanted to include "Change package name" which is off by default

**Comment by taku-nm** [comment]
I am able to reproduce this issue. The issue comes from the "Change package name" patch. Since it is a universal one, it is not guaranteed to work.
This is not related to auto-cli as this is a patches issue in itself. I doubt this would get fixed tho, after all the patch has not been specifically made for TikTok
