### ISSUE TITLE
Instagram not starting

### ISSUE THREAD

**Issue by CrazyWolf13** [taku-nm/auto-cli#33]
Hi 
If I install instagram apk made with your tool it won't launch,. it shows app needs an update.

**Comment by taku-nm** [comment]
I cannot reproduce this issue on my side. Running Android 14 it warns me that the app is not compatible with my current android version, but it works just fine...

OS: Android 14
Vendor: Sony
Geo Europe

This issue is certainly related to [2739](https://github.com/ReVanced/revanced-patches/issues/2739)

Since the app works on my phone at least, I will keep it in the list for the time being until we know what android versions are affected by this. Based on that I will either keep it with additional information added to the list or remove it entirely.

@CrazyWolf13 please report your phone vendor and android version

**Comment by CrazyWolf13** [comment]
> d by this. Based on that I will either keep it with additional information added to the list or remove it entirely.

Strange, on my phone I cannot use it at all, exactly like the issue linked.

OS: Android 14
Vendor: Samsung
Geo: Europe

**Comment by panagiotis94** [comment]
I have the same problem for a few days now. 



OS: Android 10
Vendor: Huawei 
Geo: Europe

**Comment by taku-nm** [comment]
> I have the same problem for a few days now.
> 
> OS: Android 10 Vendor: Huawei Geo: Europe

Make sure to include the information on what device you have in the patches repo

**Comment by CrazyWolf13** [comment]
> > I have the same problem for a few days now.
> > OS: Android 10 Vendor: Huawei Geo: Europe
> 
> Make sure to include the information on what device you have in the patches repo

Got marked as off topic.

**Comment by taku-nm** [comment]
The issue now occurs for me as well; therefore I can no longer consider Instagram to be validated as working.
Will get removed soon

**Comment by CrazyWolf13** [comment]
> The issue now occurs for me as well; therefore I can no longer consider Instagram to be validated as working. Will get removed soon

Could you readd instagram? Seems to have gotten fixed by a new commit.

**Comment by taku-nm** [comment]
Yes ofc it will be re-added but the fix is less than an hour old. _maybe_ I will get to it today.
